export const ROMAN_FACTS = [
  'Rome traditionally dated its founding to 753 BCE.',
  'The Romans told a story that Romulus and Remus were raised by a she-wolf.',
  'The Roman Republic began after the last king was expelled in 509 BCE.',
  'SPQR stands for the Senate and People of Rome.',
  'Roman roads were built with drainage, layers of stone, and a slight crown.',
  'Some Roman roads are still visible after nearly two thousand years.',
  'The Appian Way was one of Rome’s earliest and most famous highways.',
  'Roman concrete could set underwater, which helped build ports and harbors.',
  'The Pantheon has the world’s largest unreinforced concrete dome.',
  'The Pantheon’s oculus is open to the sky.',
  'Aqueducts used gentle gravity-fed slopes to move water over long distances.',
  'The city of Rome had hundreds of public fountains.',
  'Roman bathhouses were social centers, not just places to wash.',
  'Hypocaust systems heated floors and walls in baths and villas.',
  'Roman mosaics were made from tiny pieces called tesserae.',
  'Pompeii was buried by Mount Vesuvius in 79 CE.',
  'Graffiti found at Pompeii preserves jokes, ads, names, and insults.',
  'Roman shops often opened directly onto the street.',
  'Many Romans lived in apartment blocks called insulae.',
  'Wealthy Roman homes often had an atrium near the entrance.',
  'Latin was the language of government and law in the western empire.',
  'Greek remained hugely important in the eastern Roman world.',
  'The Roman Empire reached its greatest territorial extent under Trajan.',
  'Trajan’s Column tells a military story in a spiraling stone relief.',
  'Julius Caesar was never emperor, though later emperors used Caesar as a title.',
  'Augustus was Rome’s first emperor.',
  'Augustus claimed he found Rome brick and left it marble.',
  'The Pax Romana describes a long period of relative imperial stability.',
  'Roman emperors often minted coins to spread political messages.',
  'Coin portraits helped people recognize rulers they would never meet.',
  'The Colosseum could hold tens of thousands of spectators.',
  'The Colosseum’s real ancient name was the Flavian Amphitheatre.',
  'Gladiators were trained fighters, not always condemned prisoners.',
  'Some gladiators became famous celebrities.',
  'Chariot racing was often more popular than gladiator games.',
  'The Circus Maximus was Rome’s huge chariot-racing venue.',
  'Chariot teams were associated with colors such as blue, green, red, and white.',
  'Roman numerals do not have a true zero.',
  'The Romans used abacuses and counting boards for calculations.',
  'Roman calendars were reformed by Julius Caesar.',
  'The Julian calendar influenced calendars for many centuries.',
  'July is named after Julius Caesar.',
  'August is named after Augustus.',
  'Roman law strongly influenced later European legal systems.',
  'The Twelve Tables were an early written Roman law code.',
  'Roman citizenship expanded over time across the empire.',
  'In 212 CE, Caracalla extended citizenship to nearly all free people in the empire.',
  'Roman soldiers served in legions made up of thousands of troops.',
  'A legion’s eagle standard was a powerful symbol of honor.',
  'Roman soldiers helped build roads, forts, and walls.',
  'Hadrian’s Wall marked a northern frontier in Britain.',
  'The Romans called the Mediterranean Sea Mare Nostrum, meaning Our Sea.',
  'Roman trade moved olive oil, wine, grain, pottery, metals, and luxury goods.',
  'Grain shipments from Egypt helped feed the city of Rome.',
  'Ostia was Rome’s major port near the mouth of the Tiber.',
  'Roman amphorae were used to transport liquids and foods.',
  'Broken pottery from amphorae formed Rome’s Monte Testaccio hill.',
  'Garum was a popular fermented fish sauce.',
  'Romans reclined while dining at formal banquets.',
  'A triclinium was a Roman dining room with couches.',
  'Bread, olives, wine, cheese, and legumes were common foods.',
  'Roman wine was often mixed with water.',
  'Public toilets existed in many Roman towns.',
  'Romans used sponge sticks in public latrines.',
  'Roman bath complexes could include hot, warm, and cold rooms.',
  'The Latin word forum meant a public square or marketplace.',
  'The Roman Forum was the political and ceremonial heart of Rome.',
  'Triumphal arches celebrated military victories and imperial power.',
  'A triumph was an elaborate victory procession through Rome.',
  'Purple dye was associated with wealth and status.',
  'Togas were formal garments for Roman citizens.',
  'Most daily Roman clothing was simpler than a toga.',
  'Roman women often wore a garment called a stola.',
  'Roman children could wear protective amulets called bullae.',
  'Saturnalia was a festive Roman holiday in December.',
  'During Saturnalia, gifts and role reversals were part of the fun.',
  'The Romans adopted and adapted many Greek gods and myths.',
  'Jupiter was king of the Roman gods.',
  'Minerva was associated with wisdom, crafts, and strategy.',
  'Mars was a major Roman god connected with war.',
  'Vesta’s sacred fire was kept by the Vestal Virgins.',
  'The Vestal Virgins held unusual religious prestige in Rome.',
  'Roman religion included household gods called Lares and Penates.',
  'Emperor worship became part of imperial public religion.',
  'Christianity began as a small movement inside the Roman Empire.',
  'Constantine legalized Christianity with the Edict of Milan in 313 CE.',
  'Constantinople was founded as a new imperial capital in 330 CE.',
  'The eastern Roman Empire continued long after the western empire fell.',
  'Byzantine is a modern label for the medieval eastern Roman Empire.',
  'The western Roman Empire is often dated as ending in 476 CE.',
  'Roman arches allowed builders to span large spaces.',
  'Vaults and domes were Roman architectural superpowers.',
  'Roman theaters were often freestanding stone structures.',
  'Amphitheatres were oval arenas used for public spectacles.',
  'Roman mile markers helped travelers track distances.',
  'The word mile comes from the Latin for one thousand paces.',
  'Roman doctors used surgical tools that look surprisingly familiar.',
  'Roman glassmakers produced bottles, cups, and window glass.',
  'Romans used wax tablets for notes and everyday writing.',
  'Styluses could write on wax and smooth it again for reuse.',
  'Papyrus and parchment were used for longer texts.',
  'Libraries existed in Rome and major provincial cities.',
  'Virgil wrote the Aeneid, Rome’s great national epic.',
  'Ovid, Horace, and Livy wrote during the age of Augustus.',
  'Cicero was famous for speeches, philosophy, and letters.',
  'Roman names often included personal, family, and branch names.',
  'Freed formerly enslaved people could become Roman citizens.',
  'Roman society depended heavily on enslaved labor.',
  'Roman provinces were governed by officials sent from Rome.',
  'Local elites helped run many cities across the empire.',
  'Roman urban planning often used grid-like street layouts.',
  'Many Roman towns had public baths, forums, temples, and theaters.',
  'The empire covered parts of Europe, North Africa, and western Asia.',
];
